apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: "moxie-test-gcc"
    name: "moxie-test-gcc"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "moxie-test-gcc:latest"
    resources: {}
    source:
      git:
        ref: master
        uri: https://gogs.apps.home.labdroid.net/green/moxie-test-gcc.git
      contextDir:
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: DockerImage
          name: atgreen/moxielogic-builder-el7-base
        forcePull: true
      type: Docker
kind: List
metadata: {}
