---
- name: Test moxie gcc port
  hosts: all
  environment:
    KUBECONFIG: "/home/green/.kubeconfig"

  tasks:
    - name: Delete any existing test job
      shell: |
        oc -n moxie \
          delete job moxie-test-gcc --grace-period=0 --ignore-not-found

    - name: Template test job
      set_fact:
        management_pod: "{{ lookup('file', 'moxie-test-gcc-job.yml') }}"

    - name: Create test job
      shell: |
        echo {{ management_pod | quote }} | oc apply -f -
