---
apiVersion: v1
kind: Pod
metadata:
  name: moxie-test-gcc
  namespace: moxie
spec:
  containers:
    - name: moxie-test-gcc
      image: "docker-registry.default.svc:5000/moxie/moxie-test-gcc:latest"
      command: ["sleep", "infinity"]
      env:
        - name: MOXIELOGIC_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moxielogic-mail-password
              key: MOXIELOGIC_MAIL_PASSWORD
        - name: VAULT_MOXIEDEV_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-moxiedev-token
              key: VAULT_MOXIEDEV_TOKEN
        - name: RLGL_KEY
          valueFrom:
            secretKeyRef:
              name: rlgl-key
              key: RLGL_KEY
  restartPolicy: Never
